export const VACATION_GET_REQUEST = "VACATION_GET_REQUEST";
export const VACATION_GET_SUCCESS = "VACATION_GET_SUCCESS";
export const VACATION_GET_FAILURE = "VACATION_GET_FAILURE";

export const VACATION_ADMIN_ADDED = "VACATION_ADMIN_ADDED";
export const VACATION_ADMIN_ADDEDFALSE = "VACATION_ADMIN_ADDEDFALSE";
