export const USERS_POST_REQUEST = "USERS_POST_REQUEST";
export const USERS_POST_SUCCESS = "USERS_POST_SUCCESS";
export const USERS_POST_FAILURE = "USERS_POST_FAILURE";

export const USERS_LOGIN = "USERS_LOGIN";
export const USERS_LOGOUT = "USERS_LOGOUT";

export const USERS_REGISTERED = "USERS_REGISTERED";
export const USERS_NOTREGISTERED = "USERS_NOTREGISTERED";
